### ISSUE TITLE
How to use the source code ?

### ISSUE THREAD

**Issue by huangdengpan** [instructure/instructure-android#11]
Thank you for open source the android code !
It will be very great if we have self-hosted canvas apps.

Does it need mobile plugin?
This page not found : /api/v1/mobile_verify.json

So, could you please let me know how to install mobile plugin?

**Comment by huangdengpan** [comment]
Got it and thank you ! 
Is it possible to get a business license of the API from Instructure?

**Comment by bootstraponline** [comment]
> Is it possible to get a business license of the API from Instructure?

You could email info@canvaslms.com and ask. I'd be interested to know as well.
