### ISSUE TITLE
New Logo/Icon

### ISSUE THREAD

**Issue by desuto** [instructure/instructure-android#16]
Hi @instructure i am a graphic designer, i want to help others in graphic design.
After i reviewed your project. you have no logo on this project, therefore I want to contribute to this project by creating a new logo/icon. what do you think ? you want it ?

**Comment by bootstraponline** [comment]
I think we have official logos already for Android, they're just not in the open source repo. Thank you for the offer though!

**Comment by desuto** [comment]
ok. goodluck

**Comment by bootstraponline** [comment]
Thanks!
