### ISSUE TITLE
private_data is not included

### ISSUE THREAD

**Issue by austinoneil** [instructure/instructure-android#2]
Is there anything developers need to do to get around not having the private_data directory included in the repository?

**Comment by bootstraponline** [comment]
You'd need to recreate the private data folder & file structure using your own keys. I'll ask about open sourcing a template to make this easier once I'm back at work in January.

**Comment by austinoneil** [comment]
Thank you. Have a great break!

**Comment by bootstraponline** [comment]
FYI I have merged a fix for this internally. It'll be in the next open source release (no ETA).
