### ISSUE TITLE
How to run this apps

### ISSUE THREAD

**Issue by matheusjardimb** [instructure/instructure-android#4]
Hello there,

I have just downloaded this repo and it's not very clear to me how to run this projects. I'm trying to import it into Android Studio but the IDE isn't able to run any app (apparently missing data on gradle files).

Is it possible to add instructions into the README file?

Thanks a lot!

**Comment by bootstraponline** [comment]
I think running the apps will be difficult until the source code is updated. Hopefully that happens later this year.

**Comment by bootstraponline** [comment]
The source code has been updated. You may have better luck now.

The code is provided for reference so we don't make any guarantees about it building or running.
