### ISSUE TITLE
Source code outdated

### ISSUE THREAD

**Issue by matheusjardimb** [instructure/instructure-android#5]
Hello there,

The code in this repo is 5 months old but some apps were updated recently at Google Play.
Is there any plan to publish those fixes in here too?

Thanks a lot!

**Comment by bootstraponline** [comment]
Thank you for your interest in the Instructure Android apps. I've shared this feedback internally with the team. There's no ETA however I hope to have good news later this year.

**Comment by JordanMarshall** [comment]
Closed by https://github.com/instructure/instructure-android/pull/6/
